# Generated by CMake 3.6.1

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget cppan-helpers pvt.cppan.demo.leptonica-master pvt.cppan.demo.gif-5.1.4 pvt.cppan.demo.jpeg-9.2.0 pvt.cppan.demo.png-1.6.23 pvt.cppan.demo.tiff-4.0.6 pvt.cppan.demo.webp-0.5.1 pvt.cppan.demo.zlib-1.2.8 cppan)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target cppan-helpers
add_library(cppan-helpers INTERFACE IMPORTED)

set_target_properties(cppan-helpers PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "CPPAN;TIF_PLATFORM_CONSOLE;HAVE_FLOOR;HAVE_GETOPT;HAVE_ISASCII;HAVE_LFIND;HAVE_MEMMOVE;HAVE_MEMSET;HAVE_POW;HAVE_SETMODE;HAVE_SQRT;HAVE_STRCASECMP;HAVE_STRCHR;HAVE_STRRCHR;HAVE_STRSTR;HAVE_STRTOL;HAVE_STRTOULL;HAVE_SNPRINTF;HAVE_ASSERT_H;HAVE_FCNTL_H;HAVE_INTTYPES_H;HAVE_IO_H;HAVE_LIMITS_H;HAVE_MALLOC_H;HAVE_MEMORY_H;HAVE_SEARCH_H;HAVE_STDBOOL_H;HAVE_STDINT_H;HAVE_STDLIB_H;HAVE_STRING_H;HAVE_STRINGS_H;HAVE_SYS_STAT_H;HAVE_SYS_TIME_H;HAVE_SYS_TYPES_H;HAVE_UNISTD_H;HAVE__BOOL;HAVE_LONG_LONG_INT;HAVE_OFF_T;HAVE_PTRDIFF_T;HAVE_SIGNED_INT;HAVE_SIGNED_LONG;HAVE_SIGNED_LONG_LONG;HAVE_SIGNED_SHORT;HAVE_SIZE_T;HAVE_UNSIGNED_CHAR_P;HAVE_UNSIGNED_INT;HAVE_UNSIGNED_LONG;HAVE_UNSIGNED_LONG_LONG;HAVE_UNSIGNED_SHORT;HAVE_VOID_P;HAVE_WCHAR_T"
  INTERFACE_LINK_LIBRARIES "Ws2_32"
)

# Create imported target pvt.cppan.demo.leptonica-master
add_library(pvt.cppan.demo.leptonica-master STATIC IMPORTED)

set_target_properties(pvt.cppan.demo.leptonica-master PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "HAVE_CONFIG_H;HAVE_LIBGIF;HAVE_LIBJPEG;HAVE_LIBPNG;HAVE_LIBTIFF;HAVE_LIBWEBP;HAVE_LIBZ"
  INTERFACE_INCLUDE_DIRECTORIES "F:/tesseract/new_build/cppan/fad62e;C:/Users/user/.cppan/packages/pvt.cppan.demo.leptonica/master/src"
  INTERFACE_LINK_LIBRARIES "cppan-helpers;pvt.cppan.demo.gif-5.1.4;pvt.cppan.demo.jpeg-9.2.0;pvt.cppan.demo.png-1.6.23;pvt.cppan.demo.tiff-4.0.6;pvt.cppan.demo.webp-0.5.1"
)

# Create imported target pvt.cppan.demo.gif-5.1.4
add_library(pvt.cppan.demo.gif-5.1.4 STATIC IMPORTED)

set_target_properties(pvt.cppan.demo.gif-5.1.4 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "F:/tesseract/new_build/cppan/0376d2;C:/Users/user/.cppan/packages/pvt.cppan.demo.gif/5.1.4/lib"
  INTERFACE_LINK_LIBRARIES "cppan-helpers"
)

# Create imported target pvt.cppan.demo.jpeg-9.2.0
add_library(pvt.cppan.demo.jpeg-9.2.0 STATIC IMPORTED)

set_target_properties(pvt.cppan.demo.jpeg-9.2.0 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "F:/tesseract/new_build/cppan/eff62d;C:/Users/user/.cppan/packages/pvt.cppan.demo.jpeg/9.2.0/."
  INTERFACE_LINK_LIBRARIES "cppan-helpers"
)

# Create imported target pvt.cppan.demo.png-1.6.23
add_library(pvt.cppan.demo.png-1.6.23 STATIC IMPORTED)

set_target_properties(pvt.cppan.demo.png-1.6.23 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "F:/tesseract/new_build/cppan/fb7ec6;C:/Users/user/.cppan/packages/pvt.cppan.demo.png/1.6.23/."
  INTERFACE_LINK_LIBRARIES "cppan-helpers;pvt.cppan.demo.zlib-1.2.8"
)

# Create imported target pvt.cppan.demo.tiff-4.0.6
add_library(pvt.cppan.demo.tiff-4.0.6 STATIC IMPORTED)

set_target_properties(pvt.cppan.demo.tiff-4.0.6 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "F:/tesseract/new_build/cppan/ec64e8;C:/Users/user/.cppan/packages/pvt.cppan.demo.tiff/4.0.6/libtiff"
  INTERFACE_LINK_LIBRARIES "cppan-helpers;pvt.cppan.demo.zlib-1.2.8"
)

# Create imported target pvt.cppan.demo.webp-0.5.1
add_library(pvt.cppan.demo.webp-0.5.1 STATIC IMPORTED)

set_target_properties(pvt.cppan.demo.webp-0.5.1 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "F:/tesseract/new_build/cppan/f9a11d;C:/Users/user/.cppan/packages/pvt.cppan.demo.webp/0.5.1/src"
  INTERFACE_LINK_LIBRARIES "cppan-helpers"
)

# Create imported target pvt.cppan.demo.zlib-1.2.8
add_library(pvt.cppan.demo.zlib-1.2.8 STATIC IMPORTED)

set_target_properties(pvt.cppan.demo.zlib-1.2.8 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "F:/tesseract/new_build/cppan/821ee4;C:/Users/user/.cppan/packages/pvt.cppan.demo.zlib/1.2.8/."
  INTERFACE_LINK_LIBRARIES "cppan-helpers"
)

# Create imported target cppan
add_library(cppan INTERFACE IMPORTED)

set_target_properties(cppan PROPERTIES
  INTERFACE_LINK_LIBRARIES "pvt.cppan.demo.leptonica-master"
)

# Import target "pvt.cppan.demo.leptonica-master" for configuration ""
set_property(TARGET pvt.cppan.demo.leptonica-master APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(pvt.cppan.demo.leptonica-master PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "F:/tesseract/new_build/cppan/fad62e/libpvt.cppan.demo.leptonica-master.a"
  )

# Import target "pvt.cppan.demo.gif-5.1.4" for configuration ""
set_property(TARGET pvt.cppan.demo.gif-5.1.4 APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(pvt.cppan.demo.gif-5.1.4 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "F:/tesseract/new_build/cppan/0376d2/libpvt.cppan.demo.gif-5.1.4.a"
  )

# Import target "pvt.cppan.demo.jpeg-9.2.0" for configuration ""
set_property(TARGET pvt.cppan.demo.jpeg-9.2.0 APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(pvt.cppan.demo.jpeg-9.2.0 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "F:/tesseract/new_build/cppan/eff62d/libpvt.cppan.demo.jpeg-9.2.0.a"
  )

# Import target "pvt.cppan.demo.png-1.6.23" for configuration ""
set_property(TARGET pvt.cppan.demo.png-1.6.23 APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(pvt.cppan.demo.png-1.6.23 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "F:/tesseract/new_build/cppan/fb7ec6/libpvt.cppan.demo.png-1.6.23.a"
  )

# Import target "pvt.cppan.demo.tiff-4.0.6" for configuration ""
set_property(TARGET pvt.cppan.demo.tiff-4.0.6 APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(pvt.cppan.demo.tiff-4.0.6 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "F:/tesseract/new_build/cppan/ec64e8/libpvt.cppan.demo.tiff-4.0.6.a"
  )

# Import target "pvt.cppan.demo.webp-0.5.1" for configuration ""
set_property(TARGET pvt.cppan.demo.webp-0.5.1 APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(pvt.cppan.demo.webp-0.5.1 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "F:/tesseract/new_build/cppan/f9a11d/libpvt.cppan.demo.webp-0.5.1.a"
  )

# Import target "pvt.cppan.demo.zlib-1.2.8" for configuration ""
set_property(TARGET pvt.cppan.demo.zlib-1.2.8 APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(pvt.cppan.demo.zlib-1.2.8 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "F:/tesseract/new_build/cppan/821ee4/libpvt.cppan.demo.zlib-1.2.8.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
